name: Run static analysis
on: [pull_request]
jobs:
  run-static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm install
      - run: npm run lint:project -- --max-warnings=0
      - run: npm run format:project
      - run: npm run build
